### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by wly-ai-bj** [ufoym/imbalanced-dataset-sampler#12]
Follows your method to install the package:
git clone https://github.com/ufoym/imbalanced-dataset-sampler.git
cd imbalanced-dataset-sampler
python setup.py install
pip install .

But when I run "pip install .", I met the error as follows:
FileNotFoundError: [Errno 2] No such file or directory: '/home/miniconda3/envs/pytorch/lib/python3.7/site-packages/torchsampler-0.1-py3.7.egg'

How can I resolve it?

**Comment by Youngyif** [comment]
Excuse me, have you solved that problem, i met the same issue.

**Comment by Usernamezhx** [comment]
the same too.

**Comment by Borda** [comment]
after #24 you can simply
```bash
pip install git+https://github.com/ufoym/imbalanced-dataset-sampler.git
```
