### ISSUE TITLE
Too much time cost 

### ISSUE THREAD

**Issue by nothingeasy** [ufoym/imbalanced-dataset-sampler#21]
It slower than before too many times when I use this sampler

(self.indices[i] for i in torch.multinomial(self.weights, self.num_samples, replacement=True))
it seems that this expression cost too much time!

Any one have any solution?

**Comment by www516717402** [comment]
@nothingeasy 
In my view, **for function** is surplus. Modify as follow:
``` python
return iter(torch.multinomial(self.weights, self.num_samples, replacement=True))
```
I test this modify currently(I am not comfirm correct), and plan to write ditribute balance sampler class base this project.
