### ISSUE TITLE
latest commit cannot get correct labels from ImageFolder dataset

### ISSUE THREAD

**Issue by TriLoo** [ufoym/imbalanced-dataset-sampler#32]
the `ImageFolder.imgs` return a list of 2-element tuple, such as: 

```
[
('classA/img01.jpg', 0),
('classB/img01.jpg', 1),
...
('classN/img01.jpg', N-1)
]
```

if we use `dataset.imgs[:][1]`, it cannot not get correct labels of all samples.

at this line: https://github.com/ufoym/imbalanced-dataset-sampler/blob/756b0b61ca48a026e9a5c216296a520a10faf7df/torchsampler/imbalanced.py#L46

**Comment by LeeTaeHoon97** [comment]
Before the full-request, this is my first time, so I had to get permission before the start, but I'm sorry I couldn't. I'm really sorry if you were already proceeding. If you're still working on it, I'll close the full request I just uploaded.

**Comment by TriLoo** [comment]
I just fixed it in my case.
